export const gpaKeywords: string[] = [
    "gpa calculator",
    "college gpa calculator",
    "gpa",
    "how to calculate gpa",
    "gpa calculator college",
    "gpa scale",
    "gpa calculator high school",
    "calculate gpa",
    "summa cum laude gpa",
    "cumulative gpa calculator",
    "magna cum laude gpa",
    "high school gpa calculator",
    "what is a good gpa",
    "cum laude gpa",
    "cumulative gpa",
    "what is a gpa",
    "what is gpa",
    "whats a good gpa",
    "3.5 gpa",
    "gpa calculator middle school",
    "b+ gpa",
    "gpa calc",
    "gpa meaning",
    "average gpa",
    "highest gpa",
    "a- gpa",
    "3.0 gpa",
    "college gpa",
    "what is the highest gpa",
    "weighted vs unweighted gpa",
    "weighted gpa calculator",
    "weighted gpa",
    "whats the highest gpa",
    "4.0 gpa",
    "3.7 gpa",
    "gpa converter",
    "unweighted gpa",
    "asu gpa calculator",
    "what is cumulative gpa",
    "3.4 gpa",
    "unweighted gpa calculator",
    "3.8 gpa",
    "2.0 gpa",
    "2.5 gpa",
    "middle school gpa calculator",
    "calculate my gpa",
    "how to calculate your gpa",
    "what does gpa stand for",
    "angel reese gpa",
    "3.3 gpa",
    "unweighted vs weighted gpa",
    "4.0 gpa scale",
    "is a 3.5 gpa good",
    "3.2 gpa",
    "what is the average gpa",
    "what is a 3.0 gpa",
    "b gpa",
    "gpa to letter grade",
    "is a 3.0 gpa good",
    "what is my gpa",
    "what is a cumulative gpa",
    "how to find gpa",
    "uc gpa calculator",
    "gpa chart",
    "ut gpa calculator",
    "3.6 gpa",
    "what is a 3.5 gpa",
    "gpa scale reporting",
    "what is an average gpa",
    "good gpa",
    "what is a weighted gpa",
    "harvard gpa requirements",
    "2.8 gpa",
    "college gpa scale",
    "is 3.5 a good gpa",
    "2.7 gpa",
    "what gpa do you need to get into harvard",
    "what gpa is summa cum laude",
    "how to check your gpa",
    "med school gpa",
    "is a 3.6 gpa good",
    "what is weighted gpa",
    "how do you calculate gpa",
    "gpa conversion",
    "how is gpa calculated",
    "average college gpa",
    "is a 3.8 gpa good",
    "overall gpa calculator",
    "whats my gpa",
    "highest gpa ever",
    "is a 3.4 gpa good",
    "highschool gpa",
    "semester gpa calculator",
    "how to check gpa",
    "what is a 4.0 gpa",
    "is a 3.7 gpa good",
    "percentage to gpa calculator",
    "uf gpa calculator",
    "lsu gpa calculator",
    "cumulative gpa meaning"
];
